/**
 * WASM binding loader for browsers.
 *
 * This module provides async WASM loading for browser environments.
 * The WASM module must be initialized before use for best performance.
 */

import type { BigIntBuffer2Extended } from '../types.js';
import { fallback } from '../fallback.js';

/**
 * WASM binding interface matching the wasm-bindgen exports.
 */
interface WasmBinding {
  to_bigint_be(buffer: Uint8Array): bigint;
  to_bigint_le(buffer: Uint8Array): bigint;
  to_buffer_be(num: bigint, width: number): Uint8Array;
  to_buffer_le(num: bigint, width: number): Uint8Array;
  to_buffer_be_into(num: bigint, buffer: Uint8Array): void;
  to_buffer_le_into(num: bigint, buffer: Uint8Array): void;
  default(): Promise<void>;
}

let wasmBinding: BigIntBuffer2Extended | null = null;
let wasmLoading: Promise<BigIntBuffer2Extended> | null = null;
let loadAttempted = false;

/**
 * Load the WASM module asynchronously.
 *
 * @returns Promise resolving to the WASM implementation or fallback
 */
async function loadWasm(): Promise<BigIntBuffer2Extended> {
  try {
    // Dynamic import of the WASM module generated by wasm-pack
    // The path is resolved at runtime - the WASM module is built separately
    // @ts-expect-error - WASM module is generated at build time by wasm-pack
    const wasmModule: WasmBinding = await import('../../wasm/bigint_buffer2.js');

    // Initialize the WASM module
    await wasmModule.default();

    const binding: WasmBinding = wasmModule;

    wasmBinding = {
      toBigIntBE: (buffer: Buffer | Uint8Array) => {
        const arr = buffer instanceof Uint8Array ? buffer : new Uint8Array(buffer);
        return binding.to_bigint_be(arr);
      },
      toBigIntLE: (buffer: Buffer | Uint8Array) => {
        const arr = buffer instanceof Uint8Array ? buffer : new Uint8Array(buffer);
        return binding.to_bigint_le(arr);
      },
      toBufferBE: (num: bigint, width: number) => {
        return binding.to_buffer_be(num, width);
      },
      toBufferLE: (num: bigint, width: number) => {
        return binding.to_buffer_le(num, width);
      },
      toBufferBEInto: (num: bigint, buffer: Buffer | Uint8Array) => {
        const arr = buffer instanceof Uint8Array ? buffer : new Uint8Array(buffer);
        binding.to_buffer_be_into(num, arr);
      },
      toBufferLEInto: (num: bigint, buffer: Buffer | Uint8Array) => {
        const arr = buffer instanceof Uint8Array ? buffer : new Uint8Array(buffer);
        binding.to_buffer_le_into(num, arr);
      },
    };

    return wasmBinding;
  } catch {
    // WASM not available, return fallback
    return fallback;
  }
}

/**
 * Get the WASM implementation asynchronously.
 *
 * Call this early in your application for best performance.
 *
 * @returns Promise resolving to BigIntBuffer2Extended implementation
 */
export async function getWasm(): Promise<BigIntBuffer2Extended> {
  if (wasmBinding !== null) {
    return wasmBinding;
  }

  if (wasmLoading === null) {
    loadAttempted = true;
    wasmLoading = loadWasm().then((binding) => {
      wasmBinding = binding;
      return binding;
    });
  }

  return wasmLoading;
}

/**
 * Get the WASM implementation synchronously.
 *
 * Returns the WASM implementation if already loaded, otherwise returns fallback.
 * For best performance, call `getWasm()` or `initWasm()` first.
 *
 * @returns BigIntBuffer2Extended implementation (WASM if loaded, fallback otherwise)
 */
export function getWasmSync(): BigIntBuffer2Extended {
  return wasmBinding ?? fallback;
}

/**
 * Check if WASM bindings are available.
 *
 * @returns true if WASM bindings are loaded
 */
export function isWasmAvailable(): boolean {
  return wasmBinding !== null;
}

/**
 * Check if WASM loading has been attempted.
 *
 * @returns true if loading was attempted (success or failure)
 */
export function isWasmLoadAttempted(): boolean {
  return loadAttempted;
}

// Export synchronous API (uses fallback until WASM is loaded)
export const toBigIntBE = (buffer: Buffer | Uint8Array): bigint =>
  getWasmSync().toBigIntBE(buffer);

export const toBigIntLE = (buffer: Buffer | Uint8Array): bigint =>
  getWasmSync().toBigIntLE(buffer);

export const toBufferBE = (num: bigint, width: number): Buffer | Uint8Array =>
  getWasmSync().toBufferBE(num, width);

export const toBufferLE = (num: bigint, width: number): Buffer | Uint8Array =>
  getWasmSync().toBufferLE(num, width);

export const toBufferBEInto = (num: bigint, buffer: Buffer | Uint8Array): void =>
  getWasmSync().toBufferBEInto(num, buffer);

export const toBufferLEInto = (num: bigint, buffer: Buffer | Uint8Array): void =>
  getWasmSync().toBufferLEInto(num, buffer);
