/**
 * Type declarations for the WASM module generated by wasm-pack.
 * The actual module will be generated by wasm-pack at build time.
 */

// This declaration tells TypeScript about the WASM module structure
// The actual import path is resolved at runtime
interface WasmModule {
  to_bigint_be(buffer: Uint8Array): bigint;
  to_bigint_le(buffer: Uint8Array): bigint;
  to_buffer_be(num: bigint, width: number): Uint8Array;
  to_buffer_le(num: bigint, width: number): Uint8Array;
  default(): Promise<void>;
}
