/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Convert BigInt to BE buffer using BufferMut (minimal overhead) */
export declare function toBufferBeFast(num: bigint, buffer: BufferMut): void
/** Convert BigInt to LE buffer using BufferMut (minimal overhead) */
export declare function toBufferLeFast(num: bigint, buffer: BufferMut): void
/**
 * Convert a big-endian buffer to BigInt.
 *
 * # Arguments
 * * `buffer` - Big-endian byte buffer (accepts Buffer or Uint8Array)
 *
 * # Returns
 * BigInt value
 *
 * # Example
 * ```javascript
 * const { toBigIntBe } = require('@vekexasia/bigint-buffer2');
 * const buf = Buffer.from([0x01, 0x02, 0x03, 0x04]);
 * const num = toBigIntBe(buf); // 16909060n
 * ```
 */
export declare function toBigintBe(buffer: Uint8Array): bigint
/**
 * Convert a little-endian buffer to BigInt.
 *
 * # Arguments
 * * `buffer` - Little-endian byte buffer (accepts Buffer or Uint8Array)
 *
 * # Returns
 * BigInt value
 */
export declare function toBigintLe(buffer: Uint8Array): bigint
