name: CI checks

on:
  workflow_call:


defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node
        uses: ./.github/actions/setup-node

      - name: Run lint
        run: |
          yarn lint
  build:
    name: "Compile Typescript"
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node
        uses: ./.github/actions/setup-node

      - name: Build Typescript
        run: |
          yarn build

